### ISSUE TITLE
Run arpeggio from external app

### ISSUE THREAD

**Issue by eusebiu** [PDBeurope/arpeggio#2]
Hi,
I am trying to run arpeggio after installing it using miniconda but I get an error:

(base) C:\>arpeggio -h
'arpeggio' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\>conda list
.# packages in environment at C:\ProgramData\Miniconda3:
.#
.# Name                    Version                   Build  Channel
arpeggio                  1.4.1                    pypi_0    pypi
biopython                 1.77                     pypi_0    pypi
bzip2                     1.0.8                he774522_0

How can I run arpeggio? I am interested in executing it from an external application.

Thanks!

**Comment by lpravda** [comment]
Hi @eusebiu , thank you for getting touch with us. 

I assume that you are using Windows. Apparently python packages works a bit differently on windows, I have improved the setup script and tested it on windows server, if you pip install it like this:

```
pip install git+https://github.com/PDBeurope/arpeggio.git@master#egg=arpeggio
```
arpeggio -h

correctly displays what is supposed to be displayed, please let me know if this works for you.

**Comment by lpravda** [comment]
Question out of curiosity, is the other application written in python 3.6+? If so I could put together a short snippet how you can run the main functions and get the result in memory so that you can work with it.

**Comment by eusebiu** [comment]
Hey @lpravda ,

Thank you for the quick reply!
After installing the openbabel from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#openbabel and installing the arpeggio with your command, I was able to run arpeggio -h from command line.

The other app is a dotnet core app and I plan to execute arpeggio similar to the  command line approach.

Thank you!
